<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Diyarak.Market.Listing</AssemblyName>
    <RootNamespace>Diyarak.Market.Listing</RootNamespace>
    <Description>Listing module for Diyarak Market.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Foundation\Diyarak.Platform.SharedKernel\Diyarak.Platform.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Foundation\Diyarak.Platform.Domain.Primitives\Diyarak.Platform.Domain.Primitives.csproj" />
  </ItemGroup>
</Project>
