// <auto-generated />
using System;
using Diyarak.Platform.Persistence.PostgreSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Diyarak.Platform.Persistence.PostgreSql.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260909221256_MarketPropertyPersistenceBaseline")]
    partial class MarketPropertyPersistenceBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Diyarak.Platform.Persistence.PostgreSql.Market.MarketPropertyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("BathroomCount")
                        .HasColumnType("integer")
                        .HasColumnName("bathroom_count");

                    b.Property<int?>("BedroomCount")
                        .HasColumnType("integer")
                        .HasColumnName("bedroom_count");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<int?>("CommercialSubtype")
                        .HasColumnType("integer")
                        .HasColumnName("commercial_subtype");

                    b.Property<int?>("ConstructionYear")
                        .HasColumnType("integer")
                        .HasColumnName("construction_year");

                    b.PrimitiveCollection<int[]>("Features")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("features");

                    b.Property<int?>("FurnishingQuality")
                        .HasColumnType("integer")
                        .HasColumnName("furnishing_quality");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("house_number");

                    b.Property<int?>("LastModernizationYear")
                        .HasColumnType("integer")
                        .HasColumnName("last_modernization_year");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<int?>("LivingAreaUnit")
                        .HasColumnType("integer")
                        .HasColumnName("living_area_unit");

                    b.Property<decimal?>("LivingAreaValue")
                        .HasColumnType("numeric")
                        .HasColumnName("living_area_value");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<int?>("ParkingSpaceCount")
                        .HasColumnType("integer")
                        .HasColumnName("parking_space_count");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<int?>("SalesAreaUnit")
                        .HasColumnType("integer")
                        .HasColumnName("sales_area_unit");

                    b.Property<decimal?>("SalesAreaValue")
                        .HasColumnType("numeric")
                        .HasColumnName("sales_area_value");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<int?>("TotalAreaUnit")
                        .HasColumnType("integer")
                        .HasColumnName("total_area_unit");

                    b.Property<decimal?>("TotalAreaValue")
                        .HasColumnType("numeric")
                        .HasColumnName("total_area_value");

                    b.Property<decimal?>("TotalRooms")
                        .HasColumnType("numeric")
                        .HasColumnName("total_rooms");

                    b.Property<int?>("UsableAreaUnit")
                        .HasColumnType("integer")
                        .HasColumnName("usable_area_unit");

                    b.Property<decimal?>("UsableAreaValue")
                        .HasColumnType("numeric")
                        .HasColumnName("usable_area_value");

                    b.HasKey("Id");

                    b.ToTable("properties", "market");
                });
#pragma warning restore 612, 618
        }
    }
}
