// <auto-generated />
using System;
using Diyarak.Platform.Persistence.PostgreSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Diyarak.Platform.Persistence.PostgreSql.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    partial class PlatformDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Diyarak.Platform.Persistence.PostgreSql.Identity.ExternalIdentityMappingRecord", b =>
                {
                    b.Property<string>("Issuer")
                        .HasColumnType("text")
                        .HasColumnName("issuer");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Issuer", "Subject")
                        .HasName("pk_external_identity_mappings");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_external_identity_mappings_user_id");

                    b.ToTable("external_identity_mappings", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_external_identity_mappings_user_id_non_empty", "user_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("Diyarak.Platform.Persistence.PostgreSql.Market.MarketListingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("AvailableFromDate")
                        .HasColumnType("date")
                        .HasColumnName("available_from_date");

                    b.Property<string>("Headline")
                        .HasColumnType("text")
                        .HasColumnName("headline");

                    b.Property<decimal?>("PriceAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("price_amount");

                    b.Property<string>("PriceCurrency")
                        .HasColumnType("text")
                        .HasColumnName("price_currency");

                    b.Property<bool?>("PriceIsOnRequest")
                        .HasColumnType("boolean")
                        .HasColumnName("price_is_on_request");

                    b.Property<Guid>("PublisherUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("publisher_user_id");

                    b.Property<int?>("PublishingRole")
                        .HasColumnType("integer")
                        .HasColumnName("publishing_role");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_type");

                    b.Property<int?>("TransactionIntent")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_intent");

                    b.HasKey("Id");

                    b.ToTable("listings", "market");
                });

            modelBuilder.Entity("Diyarak.Platform.Persistence.PostgreSql.Market.MarketPropertyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("BathroomCount")
                        .HasColumnType("integer")
                        .HasColumnName("bathroom_count");

                    b.Property<int?>("BedroomCount")
                        .HasColumnType("integer")
                        .HasColumnName("bedroom_count");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<int?>("CommercialSubtype")
                        .HasColumnType("integer")
                        .HasColumnName("commercial_subtype");

                    b.Property<int?>("ConstructionYear")
                        .HasColumnType("integer")
                        .HasColumnName("construction_year");

                    b.PrimitiveCollection<int[]>("Features")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("features");

                    b.Property<int?>("FurnishingQuality")
                        .HasColumnType("integer")
                        .HasColumnName("furnishing_quality");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("house_number");

                    b.Property<int?>("LastModernizationYear")
                        .HasColumnType("integer")
                        .HasColumnName("last_modernization_year");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<int?>("LivingAreaUnit")
                        .HasColumnType("integer")
                        .HasColumnName("living_area_unit");

                    b.Property<decimal?>("LivingAreaValue")
                        .HasColumnType("numeric")
                        .HasColumnName("living_area_value");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<int?>("ParkingSpaceCount")
                        .HasColumnType("integer")
                        .HasColumnName("parking_space_count");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<int?>("SalesAreaUnit")
                        .HasColumnType("integer")
                        .HasColumnName("sales_area_unit");

                    b.Property<decimal?>("SalesAreaValue")
                        .HasColumnType("numeric")
                        .HasColumnName("sales_area_value");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<int?>("TotalAreaUnit")
                        .HasColumnType("integer")
                        .HasColumnName("total_area_unit");

                    b.Property<decimal?>("TotalAreaValue")
                        .HasColumnType("numeric")
                        .HasColumnName("total_area_value");

                    b.Property<decimal?>("TotalRooms")
                        .HasColumnType("numeric")
                        .HasColumnName("total_rooms");

                    b.Property<int?>("UsableAreaUnit")
                        .HasColumnType("integer")
                        .HasColumnName("usable_area_unit");

                    b.Property<decimal?>("UsableAreaValue")
                        .HasColumnType("numeric")
                        .HasColumnName("usable_area_value");

                    b.HasKey("Id");

                    b.ToTable("properties", "market");
                });
#pragma warning restore 612, 618
        }
    }
}
