<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Diyarak.Api.Tests</AssemblyName>
    <RootNamespace>Diyarak.Api.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Hosts/Diyarak.Api/Diyarak.Api.csproj" />
    <ProjectReference Include="../../../src/Application/Diyarak.Market.Application/Diyarak.Market.Application.csproj" />
    <ProjectReference Include="../../../src/Core/Diyarak.Platform.Identity/Diyarak.Platform.Identity.csproj" />
    <ProjectReference Include="../../../src/Core/Diyarak.Platform.Listing/Diyarak.Platform.Listing.csproj" />
    <ProjectReference Include="../../../src/Modules/Diyarak.Market.Listing/Diyarak.Market.Listing.csproj" />
    <ProjectReference Include="../../../src/Modules/Diyarak.Market.Property/Diyarak.Market.Property.csproj" />
  </ItemGroup>
</Project>
